### PR TITLE
Release 1.10.17

### PR DESCRIPTION
**Pull request by mattwthompson**
Based off of branch `1.x` which I think was last touched with #125

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
@conda-forge-admin, please restart ci

**Comment by mattwthompson** [comment]
@conda-forge-admin, please restart ci

**Comment by mattwthompson** [comment]
Any ideas why the [feedstock builds](https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=2633) aren't starting?

* Azure doesn't seem to be down https://azure.status.microsoft/en-us/status
* I don't see any magic in the previous 1.x PR #125

Surely I'm missing something obvious

**Comment by pavelzw** [comment]
ci seems to have recovered

**Comment by mattwthompson** [comment]
Thank you!

**Comment by mikemhenry** [comment]
I was trying to figure out why there was no 1.10.17 build for python 3.13 and it looks like there just wasn't 3.13 on CI at the time and the package wasn't noarch

**Comment by pavelzw** [comment]
Do you want to create a pr for it?

**Comment by mikemhenry** [comment]
Yah I can do it Monday if someone doesn't beat me to too it.

**Pull request merged**
