### PR TITLE
Rebuild python312

### PR DESCRIPTION
**Pull request by admirito**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (The latest version will not add support for python 3.12, so I did that manually after running smithy)
* [x] Ensured the license file is being packaged.

**Update**:
After adding a migration file in 3787338, `smithy` now generates the same files that I previously added manually.

### CODE REVIEW

**Review by pavelzw — CHANGES_REQUESTED** [review]
Don't tinker with these files manually. Instead, add a migration file like in https://github.com/conda-forge/maturin-feedstock/blob/main/.ci_support/migrations/python312.yaml and rerender.

**Comment by pavelzw** [comment]
For some reason, I cannot find pydantic in the py312 migration at https://conda-forge.org/status 🤔

**Comment by xhochy** [comment]
> For some reason, I cannot find pydantic in the py312 migration at https://conda-forge.org/status 🤔

Yes, because the recipe on main is noarch Python.

**Comment by xhochy** [comment]
..and migrations for this branch has not been activated.

**Comment by pavelzw** [comment]
Ah right, it hasn’t been activated because I converted this package in 2.x to noarch 😄

**Comment by samuelcolvin** [comment]
It might be pydantic-core you need to look at?

**Comment by admirito** [comment]
> Don't tinker with these files manually. Instead, add a migration file like in https://github.com/conda-forge/maturin-feedstock/blob/main/.ci_support/migrations/python312.yaml and rerender.

Thank you @pavelzw for the hint. I have added a new migration file for Python 3.12, and now `conda-smithy` will generate the files in the exact same way as when I manually added them (except for removing new lines at the end of the file 😛)

As @xhochy also mentioned, this is for the `1.x` branch, while the `main` branch is for the `2.x` series. However, I am now curious: are all branches handled in the same way as the main branch? Will this PR trigger a release at all?

**Comment by pavelzw** [comment]
> It might be pydantic-core you need to look at?

Pydantic-core is already migrated :)

**Comment by xhochy** [comment]
All branches on the feedstock will trigger a release. If you want to have migrations for a branch, you need to list it on `main` in `conda-forge.yml`:

```
bot:
  abi_migration_branches:
    - '1.x'
``

**Comment by pavelzw** [comment]
> Will this PR trigger a release at all?

Yes, every branch on the conda-forge repo will trigger an upload. That's why it says `Used a personal fork` in the pr checklist

**Review by pavelzw — APPROVED** [review]

**Comment by pavelzw** [comment]
> you need to list it on main in conda-forge.yml

Might be helpful for future migrations. @admirito could you do this in this pr?

**Pull request merged**
