### PR TITLE
pydantic v1.10.1

### PR DESCRIPTION
**Pull request by samuelcolvin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
Thanks @samuelcolvin! Target branch should be `conda-forge:main`, afaik.

**Comment by samuelcolvin** [comment]
> Thanks @samuelcolvin! Target branch should be `conda-forge:main`, afaik.

Good catch, not sure how that happened. Fixed.

**Comment by samuelcolvin** [comment]
Not sure why this is now failing, I'll try

@conda-forge-admin, please rerender

**Comment by davidbrochart** [comment]
@samuelcolvin I'd like to be added as a maintainer, if you agree.

**Comment by samuelcolvin** [comment]
> @samuelcolvin I'd like to be added as a maintainer, if you agree.

Sounds good to me, it seems I'm not an admin on this repo, so I can't add you myself - how do we get you added?

Would you like to be added to the pydantic org too?

**Comment by davidbrochart** [comment]
> Sounds good to me, it seems I'm not an admin on this repo, so I can't add you myself - how do we get you added?

It's just a matter of adding `davidbrochart` [here](https://github.com/conda-forge/pydantic-feedstock/blob/b0c43adf60515c99009e0f1aa90b2a58cc5c06f9/recipe/meta.yaml#L49-L51). I'll open a PR.

> Would you like to be added to the pydantic org too?

Why not, although I've never contributed to pydantic, but maybe that will encourage me to do so!

**Comment by dgasmith** [comment]
Can I be part of the org too? I have been meaning to get back around to upstreaming a few more Field Types that I have built internally.

**Comment by samuelcolvin** [comment]
will do.

**Pull request merged**
