### PR TITLE
Bump to 1.10.16

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by pavelzw** [comment]
ahh, that's the reason 👍🏻

**Comment by jaimergp** [comment]
Thanks @pavelzw. Also check https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/779 to cover the previous versions.

**Comment by ytausch** [comment]
> @ytausch do you know why the autotickbot doesn't work here?

As far as I understand, it's an inherent limitation of the bot that it can track one version per feedstock repository (not even output!) only. If there is 2.x, it is impossible for the bot to make PRs for new 1.x releases. Improving this is on my roadmap.

**Comment by ytausch** [comment]
XRef: https://github.com/regro/cf-scripts/issues/2700

**Pull request merged**
