### PR TITLE
Adds cython builds

### PR DESCRIPTION
**Pull request by dgasmith**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

Adds python builds for better performance and expands testing.

### CODE REVIEW

**Comment by dgasmith** [comment]
Ok... so we timed out after 6 hours on windows. Going to remove windows compiled builds.

**Comment by samuelcolvin** [comment]
> Ok... so we timed out after 6 hours on windows. Going to remove windows compiled builds.

:+1: the log won't load for me so hard to know what went wrong.

**Comment by dgasmith** [comment]
Looks like I was caught in a loop:
```
   Compiling pydantic\__init__.py because it changed.
    Compiling pydantic\class_validators.py because it changed.
    Compiling pydantic\color.py because it changed.
    Compiling pydantic\dataclasses.py because it changed.
    Compiling pydantic\datetime_parse.py because it changed.
    Compiling pydantic\env_settings.py because it changed.
    Compiling pydantic\error_wrappers.py because it changed.
    Compiling pydantic\errors.py because it changed.
    Compiling pydantic\fields.py because it changed.
    Compiling pydantic\json.py because it changed.
    Compiling pydantic\main.py because it changed.
    Compiling pydantic\parse.py because it changed.
    Compiling pydantic\schema.py because it changed.
    Compiling pydantic\types.py because it changed.
    Compiling pydantic\utils.py because it changed.
    Compiling pydantic\validators.py because it changed.
    Compiling pydantic\version.py because it changed.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\spawn.py", line 105, in spawn_main
        exitcode = _main(fd)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\spawn.py", line 114, in _main
        prepare(preparation_data)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\spawn.py", line 225, in prepare
        _fixup_main_from_path(data['init_main_from_path'])
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
        run_name="__mp_main__")
      File "D:\bld\pydantic_1562591532638\_h_env\lib\runpy.py", line 263, in run_path
        pkg_name=pkg_name, script_name=fname)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-req-build-t2t04dbv\setup.py", line 63, in <module>
        compiler_directives=compiler_directives,
      File "D:\bld\pydantic_1562591532638\_h_env\lib\site-packages\Cython\Build\Dependencies.py", line 1073, in cythonize
        nthreads, initializer=_init_multiprocessing_helper)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\context.py", line 119, in Pool
        context=self.get_context())
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\pool.py", line 175, in __init__
        self._repopulate_pool()
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\pool.py", line 236, in _repopulate_pool
        self._wrap_exception)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\pool.py", line 255, in _repopulate_pool_static
        w.start()
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\process.py", line 105, in start
        self._popen = self._Popen(self)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\context.py", line 322, in _Popen
        return Popen(process_obj)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
        prep_data = spawn.get_preparation_data(process_obj._name)
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
        _check_not_importing_main()
      File "D:\bld\pydantic_1562591532638\_h_env\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
        is not going to be frozen to produce an executable.''')
    RuntimeError:
            An attempt has been made to start a new process before the
            current process has finished its bootstrapping phase.

            This probably means that you are not using fork to start your
            child processes and you have forgotten to use the proper idiom
            in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce an executable.
```

this was repeated ~50 times.

Ok to merge Linux/OSX builds and hack at this later?

**Comment by samuelcolvin** [comment]
yup, sounds good to me.

**Pull request merged**
