### PR TITLE
pydantic v2.0

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pavelzw** [comment]
Depends on https://github.com/conda-forge/pydantic-core-feedstock/pull/43

**Comment by 0xbe7a** [comment]
@conda-forge-admin, please restart ci

**Comment by pavelzw** [comment]
@conda-forge-admin, please restart ci

**Comment by dgasmith** [comment]
Awesome to see! Send me a ping once you have the builds passing or need a hand.

**Comment by pavelzw** [comment]
@dgasmith ready 🚀

**Pull request merged**
